### ISSUE TITLE
Counters and gauges on 32 bit platforms are limited

### ISSUE THREAD

**Issue by waywardmonkeys** [posix4e/rust-metrics#40]
Now that counters (and momentarily) gauges are using `usize` and `isize` respectively, they're limited when used on 32 bit platforms. It would be nice if we had a better solution here that wasn't terribly costly.

**Comment by arthurprs** [comment]
I think the most reasonable option is to use a spinlock along side a u64 in these platforms.

**Comment by posix4e** [comment]
I'd like to understand what performance problem we are solving but that
sounds ok.

**Comment by arthurprs** [comment]
We could use this crate or create a module like https://github.com/obourgain/rust-atomic64/blob/master/src/atomic64.rs

**Comment by posix4e** [comment]
Focusing on tic
