### ISSUE TITLE
API change ideas

### ISSUE THREAD

**Issue by waywardmonkeys** [posix4e/rust-metrics#55]
I've been trying to iteratively simplify the API, but it has proved to be rather hard to do in pieces and might require just a big set of changes.

1) Remove Registry and just let the Reporter store the metrics that it will report on.
2) Remove the `enum Metric` and add a `trait Metric` which we will `impl` from our various metrics.
3) Have the Reporter store an `Arc<Metric>` instead of the `Metric` directly.
4) Switch from pattern matching on `Metric::*` to using double dispatch so we have a `report` method on each metric type which calls back to a type specific function on the reporter. (so, `Meter::report(reporter)` would call `reporter.report_meter` which would do the right thing. Now, reporting in a loop is just iterating over the metrics and calling `report` on them...)
5) Separate reporting from spawning a thread so that a reporting cycle can be triggered independently of the thread being created. (This will let us improve testing.)

**Comment by waywardmonkeys** [comment]
Having the `Reporter` instance store metrics on its own lets it optimize that for itself and its own needs ... so things that don't need labels don't have to know about them. And the Carbon reporter will be able to improve how it does prefixing since it can then prefix on adding the metric rather than at every report cycle.

**Comment by waywardmonkeys** [comment]
https://github.com/waywardmonkeys/rust-metrics/commit/65f6b0b68e4135a86232e554b1292a69c8f4b88e is a start on some of this.

**Comment by posix4e** [comment]
Looking good

**Comment by posix4e** [comment]
+1 on getting rid of registry btw
