### ISSUE TITLE
Console reporter only prints once

### ISSUE THREAD

**Issue by whitfin** [posix4e/rust-metrics#84]
Pretty sure this is a bug because I'm also getting it with `bin/webserver_with_stdout`.  If you run the console report, it logs the first time and then never logs again. 

```
WebServer Starting
name: meter labels: None
MeterSnapshot { count: 100, rates: [0.0, 0.0, 0.0], mean: 400402.0036116261 }
name: counter labels: None
CounterSnapshot { value: 3876873 }
name: guage labels: None
GaugeSnapshot { value: 1 }
name: histo labels: None
histogram(1 total)
```

**Comment by posix4e** [comment]
Thanks for the report

**Comment by whitfin** [comment]
@posix4e I've looked into it a little and it looks like the `for metric in &rx` that's in the reporter just doesn't fire after the first cycle of the `while`. No idea how to fix it though, but I'll keep looking.

**Comment by posix4e** [comment]
Thanks isaac, hit me up if you get stuck
